### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by derech1e** [Hippo/HippoConfig#1]
Can you add some examples?
Can you explain, when the default config is loaded.

Thank you!

**Comment by Hippo** [comment]
Hello!

Thank you for your suggestion, they are always greatly appreciated.

I added an example case in the form of a bukkit plugin [here](https://github.com/Hippo/HippoConfig/tree/master/Examples).
There is comments throughout the code which should explain how to use the library thoroughly.

If you have any more questions feel free to let me know, if not just close this issue.
Thank you 😄

**Comment by derech1e** [comment]
> Hello!
> 
> 
> 
> Thank you for your suggestion, they are always greatly appreciated.
> 
> 
> 
> I added an example case in the form of a bukkit plugin [here](https://github.com/Hippo/HippoConfig/tree/master/Examples).
> 
> There is comments throughout the code which should explain how to use the library thoroughly.
> 
> 
> 
> If you have any more questions feel free to let me know, if not just close this issue.
> 
> Thank you 😄

Thank you very much!
